"""Adicionando coluna tipo em usuário

Revision ID: 32baed167dee
Revises: d923bf7c2040
Create Date: 2025-04-07 10:06:17.598691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32baed167dee'
down_revision: Union[str, None] = 'd923bf7c2040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tipo', sa.Enum('professor', 'aluno', 'adm', name='tipo'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tipo')
    # ### end Alembic commands ###
